---
# Source: heapster/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: heapster
    chart: heapster-1.0.2
    heritage: Tiller
    release: release-name
  name: release-name-heapster
---
# Source: heapster/templates/heapster-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: heapster
    chart: heapster-1.0.2
    heritage: Tiller
    release: release-name
  name: release-name-heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
  - kind: ServiceAccount
    name: release-name-heapster
    namespace: default
---
# Source: heapster/templates/pod-nanny-role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: release-name-heapster-pod-nanny
  labels:
    app: heapster
    chart: heapster-1.0.2
    heritage: Tiller
    release: release-name
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  verbs:
  - get
  - update
---
# Source: heapster/templates/pod-nanny-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: release-name-heapster-pod-nanny
  labels:
    app: heapster
    chart: heapster-1.0.2
    heritage: Tiller
    release: release-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-heapster-pod-nanny
subjects:
- kind: ServiceAccount
  name: release-name-heapster
  namespace: default
---
# Source: heapster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: heapster
  labels:
    chart: "heapster-1.0.2"
    app: release-name-heapster
    heritage: "Tiller"
    release: "release-name"
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: release-name-heapster

---
# Source: heapster/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-heapster
  annotations:
    {}

  labels:
    chart: "heapster-1.0.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-name-heapster
  template:
    metadata:
      annotations:
        {}

      labels:
        app: release-name-heapster
    spec:
      serviceAccountName: release-name-heapster
      containers:
      - name: heapster
        image: "k8s.gcr.io/heapster-amd64:v1.5.4"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 180
          timeoutSeconds: 5
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

        command:
          - "/heapster"
          - "--source=kubernetes.summary_api:''"

      - name: heapster-nanny

        image: "k8s.gcr.io/addon-resizer:1.7"
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              cpu: 50m
              memory: 90Mi
            requests:
              cpu: 50m
              memory: 90Mi

        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - "/pod_nanny"
          - "--deployment=release-name-heapster"
          - "--container=heapster"
          - "--cpu=150m"
          - "--extra-cpu=10m"
          - "--memory=200Mi"
          - "--extra-memory=6Mi"
          - "--threshold=5"
          - "--poll-period=300000"
